name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   build_integration_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install

    - name: Run tests
      env:
        TEST_URL: 'https://myhealthapp-test.netlify.app/' # URL als Umgebungsvariable
      run: npm test

 
   snyk-security-scan:
    needs: build_integration_test
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Scan for Security Issues
        run: snyk code test --severity-threshold=medium

      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        
   zap-basic-scan:
    needs: build_integration_test
    runs-on: ubuntu-latest
   
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'https://myhealthapp-test.netlify.app/'

